import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import SearchBar from "@/components/SearchBar";
import Coins from "@/components/Coins";
import CoinList from "@/components/CoinList";
import Layout from "@/components/Layout";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ coins }) {
  const [searchtxt, setSearchtxt] = useState("");
  const allCoins = coins.filter((coin) => coin.name.includes(searchtxt.toLowerCase()));
  // console.log(coins);
  const handleChange = (e) => {
    setSearchtxt(e.target.value);
  };
  return (
    <>
      <Layout>
        <div className="coin_app">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          {/* <main> */}
          <SearchBar onChange={handleChange} placeholder="Search" />
          <CoinList coins={allCoins} /> 
          {/* coins */}
          {/* </main> */}
        </div>
      </Layout>
    </>
  );
}
// change alot
export const getServerSideProps = async () => {
  // export async function getServerSideProps() {
  let coins = await fetch(
    `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false`
  );
  coins = await coins.json();
  return {
    props: {
      coins,
    },
  };
};
